# Deep Neural Network com Pytorch

# Sumário
## Semana 1
### 1.1 [Tensores 1D](#tensores-1d)
### 1.2 [Tensores Bidimensionais](#tensores-bidimensionais)
### 1.3 [Derivativos no Pytorch](#derivativos-no-pytorch)
### 1.4 [Conjunto de Dados Simples](#conjunto-de-dados-simples)
### 1.5 [Conjunto de Dados](#conjunto-de-dados)

## Semana 2
### 2.1 [Regressão Linear em 1D](#regressão-linear-em-1d)
### 2.2 [Treinamento de Regressão Linear](#treinamento-de-regressão-linear)
### 2.3 [Gradiente Descendente e Custo](#gradiente-descendente-e-custo)
### 2.4 [Pytorch Slope](#pytorch-slope)
### 2.5 [Treinamento de Regressão Linear (repetição)](#treinamento-de-regressão-linear-repetição)
### 2.6 [Gradiente Descendente Estocástico e o Carregador de Dados](#gradiente-descendente-estocástico-e-o-carregador-de-dados)
### 2.7 [Mini-Batch Gradient Descent](#mini-batch-gradient-descent)
### 2.8 [Otimização no Pytorch](#otimização-no-pytorch)
### 2.9 [Treinamento, Validação e Divisão de Dados](#treinamento-validação-e-divisão-de-dados)

## Semana 3
### 3.1 [Regressão Linear Múltipla](#regressão-linear-múltipla)
### 3.2 [Regressão Linear de Múltiplas Saídas](#regressão-linear-de-múltiplas-saídas)
### 3.3 [Regressão Logística para Classificação](#regressão-logística-para-classificação)

## Semana 4
### 4.1 [Previsão Softmax](#previsão-softmax)
### 4.2 [Função Softmax](#função-softmax)
### 4.3 [Softmax Pytorch](#softmax-pytorch)
### 4.4 [Redes Neurais Rasas](#redes-neurais-rasas)

## Semana 5
### 5.1 [Redes Neurais Profundas](#redes-neurais-profundas)
### 5.2 [Desistência](#desistência)
### 5.3 [Pesos e Inicialização da Rede Neural](#pesos-e-inicialização-da-rede-neural)
### 5.4 [Gradient Descent com Momentum](#gradient-descent-com-momentum)
### 5.5 [Normalização em Lote](#normalização-em-lote)

## Semana 6
### 6.1 [Convolução](#convolução)
### 6.2 [Funções de Ativação e Max Polling](#funções-de-ativação-e-max-polling)
### 6.3 [Vários Canais de Entrada e Saída](#vários-canais-de-entrada-e-saída)
### 6.4 [Rede Neural Convolucional](#rede-neural-convolucional)
### 6.5 [Modelos de Visão de Lanterna](#modelos-de-visão-de-lanterna)

## Semana 1

### Tensores 1D

Em PyTorch, tensores são estruturas fundamentais que representam dados multi-dimensionais, semelhantes a arrays ou matrizes em outras linguagens. Eles são a base para a construção e manipulação de modelos de aprendizado de máquina e redes neurais profundas. Aqui estão alguns pontos importantes sobre tensores em PyTorch:

1. **Similaridade com NumPy:** PyTorch tensores são semelhantes aos arrays do NumPy e, muitas vezes, podem ser convertidos de um para o outro. Isso facilita a integração com bibliotecas científicas em Python.

2. **Suporte a GPU:** PyTorch permite a computação em GPUs para acelerar operações. Os tensores podem ser movidos para uma GPU para aproveitar o poder de processamento paralelo.

3. **Operações Matemáticas:** PyTorch fornece uma ampla variedade de operações matemáticas que podem ser aplicadas a tensores. Isso inclui operações aritméticas, funções trigonométricas, álgebra linear, entre outras.

4. **Autograd:** Uma característica fundamental é o sistema de autograd, que automaticamente calcula gradientes para tensores. Isso é crucial para a otimização de modelos de aprendizado de máquina.

5. **Criação de Tensores:** Você pode criar tensores de várias maneiras, seja inicializando-os com valores específicos, gerando números aleatórios, ou a partir de dados existentes.

Exemplo de criação de um tensor em PyTorch:

```python
import torch

# Criando um tensor com valores específicos
tensor_exemplo = torch.tensor([[1, 2, 3], [4, 5, 6]])

print(tensor_exemplo)
```

Este é um conceito básico, e há muito mais para explorar ao trabalhar com tensores em PyTorch, especialmente ao construir e treinar redes neurais profundas. Se tiver mais perguntas ou se quiser abordar aspectos específicos, sinta-se à vontade para perguntar!

Tensores 1D em PyTorch são estruturas de dados unidimensionais que podem armazenar uma sequência de elementos. Esses tensores são semelhantes a vetores ou listas unidimensionais em outras linguagens de programação. Eles são úteis para representar dados ao longo de uma única dimensão, como séries temporais, uma linha de pixels de uma imagem ou um conjunto de valores.

Aqui está um exemplo de como criar e trabalhar com um tensor 1D em PyTorch:

```python
import torch

# Criando um tensor 1D
tensor_1d = torch.tensor([1, 2, 3, 4, 5])

# Acessando elementos do tensor
print(tensor_1d[0])  # Saída: 1
print(tensor_1d[2])  # Saída: 3

# Operações matemáticas em tensores 1D
tensor_resultado = tensor_1d * 2
print(tensor_resultado)  # Saída: tensor([2, 4, 6, 8, 10])
```

Neste exemplo, `tensor_1d` é um tensor 1D contendo os valores de 1 a 5. Você pode acessar elementos individualmente e realizar operações matemáticas diretamente nos tensores.

Os tensores 1D são frequentemente usados em problemas onde os dados estão organizados de forma linear, e são a base para a construção de estruturas de dados mais complexas, como matrizes bidimensionais (tensores 2D) e tensores de ordens superiores.

### Tensores Bidimensionais

Tensores bidimensionais em PyTorch são estruturas de dados que representam matrizes, ou seja, arranjos retangulares de elementos organizados em duas dimensões. Eles são comumente utilizados para representar dados tabulares, imagens, ou qualquer outra informação que possa ser organizada em linhas e colunas.

Aqui está um exemplo básico de criação e manipulação de um tensor bidimensional em PyTorch:

```python
import torch

# Criando um tensor bidimensional (matriz)
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acessando elementos do tensor bidimensional
print(tensor_2d[0, 1])  # Saída: 2 (linha 0, coluna 1)

# Operações matemáticas em tensores bidimensionais
tensor_resultado = tensor_2d * 2
print(tensor_resultado)
# Saída:
# tensor([[ 2,  4,  6],
#         [ 8, 10, 12],
#         [14, 16, 18]])
```

Neste exemplo, `tensor_2d` é uma matriz 3x3 com elementos de 1 a 9. Você pode acessar elementos individualmente usando índices de linha e coluna, e realizar operações matemáticas diretamente nos tensores bidimensionais.

Tensores bidimensionais são frequentemente usados em tarefas de processamento de imagens, onde cada elemento da matriz pode representar um pixel. Eles também são essenciais para a construção e treinamento de modelos de aprendizado de máquina, especialmente redes neurais profundas, onde as entradas muitas vezes são representadas por tensores bidimensionais.

In [15]:
## Esses são apenas alguns exemplos.
# Criando dois tensores bidimensionais
tensor_a = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor_b = torch.tensor([[7, 8, 9], [10, 11, 12]])

# Soma de tensores
soma = tensor_a + tensor_b
print("Soma:")
print(soma)

# Subtração de tensores
subtracao = tensor_a - tensor_b
print("\nSubtração:")
print(subtracao)

# Multiplicação de tensores (element-wise)
multiplicacao_elementwise = tensor_a * tensor_b
print("\nMultiplicação (element-wise):")
print(multiplicacao_elementwise)

# Multiplicação de tensores (produto matricial)
produto_matricial = torch.matmul(tensor_a, tensor_b.T)  # Transpondo tensor_b para alinhar dimensões*
print("\nProduto Matricial:")
print(produto_matricial)

# Operações de redução (somando elementos ao longo das colunas)
soma_colunas = torch.sum(tensor_a, dim=0)
print("\nSoma das Colunas:")
print(soma_colunas)

# Operações de broadcast (somando uma constante a cada elemento)
tensor_soma_constante = tensor_a + 10
print("\nSoma com Constante:")
print(tensor_soma_constante)

Soma:
tensor([[ 8, 10, 12],
        [14, 16, 18]])

Subtração:
tensor([[-6, -6, -6],
        [-6, -6, -6]])

Multiplicação (element-wise):
tensor([[ 7, 16, 27],
        [40, 55, 72]])

Produto Matricial:
tensor([[ 50,  68],
        [122, 167]])

Soma das Colunas:
tensor([5, 7, 9])

Soma com Constante:
tensor([[11, 12, 13],
        [14, 15, 16]])


Os tensores tridimensionais (tensores 3D) são utilizados para representar dados que possuem uma organização tridimensional, como volumes de imagens ou séries temporais multivariadas. Vamos criar alguns exemplos de tensores 3D em PyTorch:

In [16]:
# Criando um tensor 3D (volume)
tensor_3d = torch.tensor([[[1, 2, 3],[4, 5, 6]],
                          [[7, 8, 9], [10, 11, 12]],
                          [[13, 14, 15], [16, 17, 18]]])

# Acessando elementos do tensor 3D
print("Acessando um elemento:")
print(tensor_3d[1, 0, 2])  # Saída: 9 (depth 1, linha 0, coluna 2)

# Operações matemáticas em tensores 3D
tensor_resultado = tensor_3d * 2
print("\nMultiplicação por 2:")
print(tensor_resultado)

# Operações de redução (somando elementos ao longo das dimensões)
soma_dim1 = torch.sum(tensor_3d, dim=1)
print("\nSoma ao Longo da Dimensão 1:")
print(soma_dim1)

# Operações de broadcast (somando uma constante a cada elemento)
tensor_soma_constante = tensor_3d + 10
print("\nSoma com Constante:")
print(tensor_soma_constante)

Acessando um elemento:
tensor(9)

Multiplicação por 2:
tensor([[[ 2,  4,  6],
         [ 8, 10, 12]],

        [[14, 16, 18],
         [20, 22, 24]],

        [[26, 28, 30],
         [32, 34, 36]]])

Soma ao Longo da Dimensão 1:
tensor([[ 5,  7,  9],
        [17, 19, 21],
        [29, 31, 33]])

Soma com Constante:
tensor([[[11, 12, 13],
         [14, 15, 16]],

        [[17, 18, 19],
         [20, 21, 22]],

        [[23, 24, 25],
         [26, 27, 28]]])


Neste exemplo, tensor_3d representa um volume 3D com dimensões 3x2x3. Você pode acessar elementos individualmente usando índices em cada dimensão, e as operações matemáticas podem ser realizadas de maneira semelhante aos tensores 2D.

Os tensores 3D são frequentemente encontrados em problemas de visão computacional para representar volumes de dados tridimensionais, como pilhas de imagens ou volumes médicos. Esses exemplos básicos podem ser expandidos conforme a complexidade do problema que você está enfrentando.

### Derivativos no Pytorch

### Conjutno de Dados Simples

### Conjunto de Dados

## Semana 2

### Regressão Linear em 1D

### Treinamento de Regressão Linear

### Gradiente Descendent e Custo

### Pytorch Slope

### Treinamento de Regressao Linear

### Gradiente Descendente Estocástico e o Carregador de Dados

### Mini-Batch Gradient Descent

### Otimização no Pytorch

### Treinamento, Validação e Divisão de Dados

## Semana 3
### Regressão Linear Multipla
### Regressão Linear de Múltiplas Saídas
### Regressão Logística para Classificação

## Semana 4
### Previsão Softmax
### Função Softmax
### Softmax Pytorch
### Redes Neurais Rasas

## Semana 5
### Redes Neurais Profundas
### Desistência
### Pesos e Inicialização da Rede Neural
### Gradient Descent com Momentum
### Normalização em Lote

## Semana 6

### Convolução

### Funções de Ativação e Max Polling

### Vários Canais de Entrada e Saída

### Rede Neural Convolucional

### Modelos de Visão de Lanterna

## Modelos de Visão de Lanterna